local celadon_0 = DoorSlot("celadon","0")
local celadon_0_hub = DoorSlotHub("celadon","0",celadon_0)
celadon_0:setHubIcon(celadon_0_hub)
local celadon_1 = DoorSlot("celadon","1")
local celadon_1_hub = DoorSlotHub("celadon","1",celadon_1)
celadon_1:setHubIcon(celadon_1_hub)
local celadon_2 = DoorSlot("celadon","2")
local celadon_2_hub = DoorSlotHub("celadon","2",celadon_2)
celadon_2:setHubIcon(celadon_2_hub)
local celadon_3 = DoorSlot("celadon","3")
local celadon_3_hub = DoorSlotHub("celadon","3",celadon_3)
celadon_3:setHubIcon(celadon_3_hub)
local celadon_4 = DoorSlot("celadon","4")
local celadon_4_hub = DoorSlotHub("celadon","4",celadon_4)
celadon_4:setHubIcon(celadon_4_hub)
local celadon_5 = DoorSlot("celadon","5")
local celadon_5_hub = DoorSlotHub("celadon","5",celadon_5)
celadon_5:setHubIcon(celadon_5_hub)
local celadon_6 = DoorSlot("celadon","6")
local celadon_6_hub = DoorSlotHub("celadon","6",celadon_6)
celadon_6:setHubIcon(celadon_6_hub)
local celadon_7 = DoorSlot("celadon","7")
local celadon_7_hub = DoorSlotHub("celadon","7",celadon_7)
celadon_7:setHubIcon(celadon_7_hub)
local celadon_8 = DoorSlot("celadon","8")
local celadon_8_hub = DoorSlotHub("celadon","8",celadon_8)
celadon_8:setHubIcon(celadon_8_hub)
local celadon_9 = DoorSlot("celadon","9")
local celadon_9_hub = DoorSlotHub("celadon","9",celadon_9)
celadon_9:setHubIcon(celadon_9_hub)
local celadon_10 = DoorSlot("celadon","10")
local celadon_10_hub = DoorSlotHub("celadon","10",celadon_10)
celadon_10:setHubIcon(celadon_10_hub)
