local cerulean_cave_0 = DoorSlot("cerulean_cave","0")
local cerulean_cave_0_hub = DoorSlotHub("cerulean_cave","0",cerulean_cave_0)
cerulean_cave_0:setHubIcon(cerulean_cave_0_hub)
local cerulean_cave_1 = DoorSlot("cerulean_cave","1")
local cerulean_cave_1_hub = DoorSlotHub("cerulean_cave","1",cerulean_cave_1)
cerulean_cave_1:setHubIcon(cerulean_cave_1_hub)
local cerulean_cave_2 = DoorSlot("cerulean_cave","2")
local cerulean_cave_2_hub = DoorSlotHub("cerulean_cave","2",cerulean_cave_2)
cerulean_cave_2:setHubIcon(cerulean_cave_2_hub)
local cerulean_cave_3 = DoorSlot("cerulean_cave","3")
local cerulean_cave_3_hub = DoorSlotHub("cerulean_cave","3",cerulean_cave_3)
cerulean_cave_3:setHubIcon(cerulean_cave_3_hub)
local cerulean_cave_4 = DoorSlot("cerulean_cave","4")
local cerulean_cave_4_hub = DoorSlotHub("cerulean_cave","4",cerulean_cave_4)
cerulean_cave_4:setHubIcon(cerulean_cave_4_hub)
