local cerulean_0 = DoorSlot("cerulean","0")
local cerulean_0_hub = DoorSlotHub("cerulean","0",cerulean_0)
cerulean_0:setHubIcon(cerulean_0_hub)
local cerulean_1 = DoorSlot("cerulean","1")
local cerulean_1_hub = DoorSlotHub("cerulean","1",cerulean_1)
cerulean_1:setHubIcon(cerulean_1_hub)
local cerulean_2 = DoorSlot("cerulean","2")
local cerulean_2_hub = DoorSlotHub("cerulean","2",cerulean_2)
cerulean_2:setHubIcon(cerulean_2_hub)
local cerulean_3 = DoorSlot("cerulean","3")
local cerulean_3_hub = DoorSlotHub("cerulean","3",cerulean_3)
cerulean_3:setHubIcon(cerulean_3_hub)
local cerulean_4 = DoorSlot("cerulean","4")
local cerulean_4_hub = DoorSlotHub("cerulean","4",cerulean_4)
cerulean_4:setHubIcon(cerulean_4_hub)
local cerulean_5 = DoorSlot("cerulean","5")
local cerulean_5_hub = DoorSlotHub("cerulean","5",cerulean_5)
cerulean_5:setHubIcon(cerulean_5_hub)
local cerulean_6 = DoorSlot("cerulean","6")
local cerulean_6_hub = DoorSlotHub("cerulean","6",cerulean_6)
cerulean_6:setHubIcon(cerulean_6_hub)
local cerulean_7 = DoorSlot("cerulean","7")
local cerulean_7_hub = DoorSlotHub("cerulean","7",cerulean_7)
cerulean_7:setHubIcon(cerulean_7_hub)
local cerulean_8 = DoorSlot("cerulean","8")
local cerulean_8_hub = DoorSlotHub("cerulean","8",cerulean_8)
cerulean_8:setHubIcon(cerulean_8_hub)
local cerulean_9 = DoorSlot("cerulean","9")
local cerulean_9_hub = DoorSlotHub("cerulean","9",cerulean_9)
cerulean_9:setHubIcon(cerulean_9_hub)
local cerulean_10 = DoorSlot("cerulean","10")
local cerulean_10_hub = DoorSlotHub("cerulean","10",cerulean_10)
cerulean_10:setHubIcon(cerulean_10_hub)
