local cinnabar_0 = DoorSlot("cinnabar","0")
local cinnabar_0_hub = DoorSlotHub("cinnabar","0",cinnabar_0)
cinnabar_0:setHubIcon(cinnabar_0_hub)
local cinnabar_1 = DoorSlot("cinnabar","1")
local cinnabar_1_hub = DoorSlotHub("cinnabar","1",cinnabar_1)
cinnabar_1:setHubIcon(cinnabar_1_hub)
local cinnabar_2 = DoorSlot("cinnabar","2")
local cinnabar_2_hub = DoorSlotHub("cinnabar","2",cinnabar_2)
cinnabar_2:setHubIcon(cinnabar_2_hub)
local cinnabar_3 = DoorSlot("cinnabar","3")
local cinnabar_3_hub = DoorSlotHub("cinnabar","3",cinnabar_3)
cinnabar_3:setHubIcon(cinnabar_3_hub)
local cinnabar_4 = DoorSlot("cinnabar","4")
local cinnabar_4_hub = DoorSlotHub("cinnabar","4",cinnabar_4)
cinnabar_4:setHubIcon(cinnabar_4_hub)
local cinnabar_5 = DoorSlot("cinnabar","5")
local cinnabar_5_hub = DoorSlotHub("cinnabar","5",cinnabar_5)
cinnabar_5:setHubIcon(cinnabar_5_hub)
local cinnabar_6 = DoorSlot("cinnabar","6")
local cinnabar_6_hub = DoorSlotHub("cinnabar","6",cinnabar_6)
cinnabar_6:setHubIcon(cinnabar_6_hub)
local cinnabar_7 = DoorSlot("cinnabar","7")
local cinnabar_7_hub = DoorSlotHub("cinnabar","7",cinnabar_7)
cinnabar_7:setHubIcon(cinnabar_7_hub)
local cinnabar_8 = DoorSlot("cinnabar","8")
local cinnabar_8_hub = DoorSlotHub("cinnabar","8",cinnabar_8)
cinnabar_8:setHubIcon(cinnabar_8_hub)
