local dotted_hole_0 = DoorSlot("dotted_hole","0")
local dotted_hole_0_hub = DoorSlotHub("dotted_hole","0",dotted_hole_0)
dotted_hole_0:setHubIcon(dotted_hole_0_hub)
local dotted_hole_1 = DoorSlot("dotted_hole","1")
local dotted_hole_1_hub = DoorSlotHub("dotted_hole","1",dotted_hole_1)
dotted_hole_1:setHubIcon(dotted_hole_1_hub)
local dotted_hole_2 = DoorSlot("dotted_hole","2")
local dotted_hole_2_hub = DoorSlotHub("dotted_hole","2",dotted_hole_2)
dotted_hole_2:setHubIcon(dotted_hole_2_hub)
local dotted_hole_3 = DoorSlot("dotted_hole","3")
local dotted_hole_3_hub = DoorSlotHub("dotted_hole","3",dotted_hole_3)
dotted_hole_3:setHubIcon(dotted_hole_3_hub)
local dotted_hole_4 = DoorSlot("dotted_hole","4")
local dotted_hole_4_hub = DoorSlotHub("dotted_hole","4",dotted_hole_4)
dotted_hole_4:setHubIcon(dotted_hole_4_hub)
local dotted_hole_5 = DoorSlot("dotted_hole","5")
local dotted_hole_5_hub = DoorSlotHub("dotted_hole","5",dotted_hole_5)
dotted_hole_5:setHubIcon(dotted_hole_5_hub)
local dotted_hole_6 = DoorSlot("dotted_hole","6")
local dotted_hole_6_hub = DoorSlotHub("dotted_hole","6",dotted_hole_6)
dotted_hole_6:setHubIcon(dotted_hole_6_hub)
local dotted_hole_7 = DoorSlot("dotted_hole","7")
local dotted_hole_7_hub = DoorSlotHub("dotted_hole","7",dotted_hole_7)
dotted_hole_7:setHubIcon(dotted_hole_7_hub)
local dotted_hole_8 = DoorSlot("dotted_hole","8")
local dotted_hole_8_hub = DoorSlotHub("dotted_hole","8",dotted_hole_8)
dotted_hole_8:setHubIcon(dotted_hole_8_hub)
local dotted_hole_9 = DoorSlot("dotted_hole","9")
local dotted_hole_9_hub = DoorSlotHub("dotted_hole","9",dotted_hole_9)
dotted_hole_9:setHubIcon(dotted_hole_9_hub)
local dotted_hole_10 = DoorSlot("dotted_hole","10")
local dotted_hole_10_hub = DoorSlotHub("dotted_hole","10",dotted_hole_10)
dotted_hole_10:setHubIcon(dotted_hole_10_hub)
local dotted_hole_11 = DoorSlot("dotted_hole","11")
local dotted_hole_11_hub = DoorSlotHub("dotted_hole","11",dotted_hole_11)
dotted_hole_11:setHubIcon(dotted_hole_11_hub)
local dotted_hole_12 = DoorSlot("dotted_hole","12")
local dotted_hole_12_hub = DoorSlotHub("dotted_hole","12",dotted_hole_12)
dotted_hole_12:setHubIcon(dotted_hole_12_hub)
local dotted_hole_13 = DoorSlot("dotted_hole","13")
local dotted_hole_13_hub = DoorSlotHub("dotted_hole","13",dotted_hole_13)
dotted_hole_13:setHubIcon(dotted_hole_13_hub)
local dotted_hole_14 = DoorSlot("dotted_hole","14")
local dotted_hole_14_hub = DoorSlotHub("dotted_hole","14",dotted_hole_14)
dotted_hole_14:setHubIcon(dotted_hole_14_hub)
local dotted_hole_15 = DoorSlot("dotted_hole","15")
local dotted_hole_15_hub = DoorSlotHub("dotted_hole","15",dotted_hole_15)
dotted_hole_15:setHubIcon(dotted_hole_15_hub)
local dotted_hole_16 = DoorSlot("dotted_hole","16")
local dotted_hole_16_hub = DoorSlotHub("dotted_hole","16",dotted_hole_16)
dotted_hole_16:setHubIcon(dotted_hole_16_hub)
local dotted_hole_17 = DoorSlot("dotted_hole","17")
local dotted_hole_17_hub = DoorSlotHub("dotted_hole","17",dotted_hole_17)
dotted_hole_17:setHubIcon(dotted_hole_17_hub)
local dotted_hole_18 = DoorSlot("dotted_hole","18")
local dotted_hole_18_hub = DoorSlotHub("dotted_hole","18",dotted_hole_18)
dotted_hole_18:setHubIcon(dotted_hole_18_hub)
local dotted_hole_19 = DoorSlot("dotted_hole","19")
local dotted_hole_19_hub = DoorSlotHub("dotted_hole","19",dotted_hole_19)
dotted_hole_19:setHubIcon(dotted_hole_19_hub)
local dotted_hole_20 = DoorSlot("dotted_hole","20")
local dotted_hole_20_hub = DoorSlotHub("dotted_hole","20",dotted_hole_20)
dotted_hole_20:setHubIcon(dotted_hole_20_hub)
local dotted_hole_21 = DoorSlot("dotted_hole","21")
local dotted_hole_21_hub = DoorSlotHub("dotted_hole","21",dotted_hole_21)
dotted_hole_21:setHubIcon(dotted_hole_21_hub)
local dotted_hole_22 = DoorSlot("dotted_hole","22")
local dotted_hole_22_hub = DoorSlotHub("dotted_hole","22",dotted_hole_22)
dotted_hole_22:setHubIcon(dotted_hole_22_hub)
local dotted_hole_23 = DoorSlot("dotted_hole","23")
local dotted_hole_23_hub = DoorSlotHub("dotted_hole","23",dotted_hole_23)
dotted_hole_23:setHubIcon(dotted_hole_23_hub)
