local five_0 = DoorSlot("five","0")
local five_0_hub = DoorSlotHub("five","0",five_0)
five_0:setHubIcon(five_0_hub)
local five_1 = DoorSlot("five","1")
local five_1_hub = DoorSlotHub("five","1",five_1)
five_1:setHubIcon(five_1_hub)
local five_2 = DoorSlot("five","2")
local five_2_hub = DoorSlotHub("five","2",five_2)
five_2:setHubIcon(five_2_hub)
local five_3 = DoorSlot("five","3")
local five_3_hub = DoorSlotHub("five","3",five_3)
five_3:setHubIcon(five_3_hub)
local five_4 = DoorSlot("five","4")
local five_4_hub = DoorSlotHub("five","4",five_4)
five_4:setHubIcon(five_4_hub)
local five_5 = DoorSlot("five","5")
local five_5_hub = DoorSlotHub("five","5",five_5)
five_5:setHubIcon(five_5_hub)
local five_6 = DoorSlot("five","6")
local five_6_hub = DoorSlotHub("five","6",five_6)
five_6:setHubIcon(five_6_hub)
