local four_0 = DoorSlot("four","0")
local four_0_hub = DoorSlotHub("four","0",four_0)
four_0:setHubIcon(four_0_hub)
local four_1 = DoorSlot("four","1")
local four_1_hub = DoorSlotHub("four","1",four_1)
four_1:setHubIcon(four_1_hub)
local four_2 = DoorSlot("four","2")
local four_2_hub = DoorSlotHub("four","2",four_2)
four_2:setHubIcon(four_2_hub)
local four_3 = DoorSlot("four","3")
local four_3_hub = DoorSlotHub("four","3",four_3)
four_3:setHubIcon(four_3_hub)
local four_4 = DoorSlot("four","4")
local four_4_hub = DoorSlotHub("four","4",four_4)
four_4:setHubIcon(four_4_hub)
local four_5 = DoorSlot("four","5")
local four_5_hub = DoorSlotHub("four","5",four_5)
four_5:setHubIcon(four_5_hub)
local four_6 = DoorSlot("four","6")
local four_6_hub = DoorSlotHub("four","6",four_6)
four_6:setHubIcon(four_6_hub)
local four_7 = DoorSlot("four","7")
local four_7_hub = DoorSlotHub("four","7",four_7)
four_7:setHubIcon(four_7_hub)
