local fuchsia_0 = DoorSlot("fuchsia","0")
local fuchsia_0_hub = DoorSlotHub("fuchsia","0",fuchsia_0)
fuchsia_0:setHubIcon(fuchsia_0_hub)
local fuchsia_1 = DoorSlot("fuchsia","1")
local fuchsia_1_hub = DoorSlotHub("fuchsia","1",fuchsia_1)
fuchsia_1:setHubIcon(fuchsia_1_hub)
local fuchsia_2 = DoorSlot("fuchsia","2")
local fuchsia_2_hub = DoorSlotHub("fuchsia","2",fuchsia_2)
fuchsia_2:setHubIcon(fuchsia_2_hub)
local fuchsia_3 = DoorSlot("fuchsia","3")
local fuchsia_3_hub = DoorSlotHub("fuchsia","3",fuchsia_3)
fuchsia_3:setHubIcon(fuchsia_3_hub)
local fuchsia_4 = DoorSlot("fuchsia","4")
local fuchsia_4_hub = DoorSlotHub("fuchsia","4",fuchsia_4)
fuchsia_4:setHubIcon(fuchsia_4_hub)
local fuchsia_5 = DoorSlot("fuchsia","5")
local fuchsia_5_hub = DoorSlotHub("fuchsia","5",fuchsia_5)
fuchsia_5:setHubIcon(fuchsia_5_hub)
local fuchsia_6 = DoorSlot("fuchsia","6")
local fuchsia_6_hub = DoorSlotHub("fuchsia","6",fuchsia_6)
fuchsia_6:setHubIcon(fuchsia_6_hub)
local fuchsia_7 = DoorSlot("fuchsia","7")
local fuchsia_7_hub = DoorSlotHub("fuchsia","7",fuchsia_7)
fuchsia_7:setHubIcon(fuchsia_7_hub)
local fuchsia_8 = DoorSlot("fuchsia","8")
local fuchsia_8_hub = DoorSlotHub("fuchsia","8",fuchsia_8)
fuchsia_8:setHubIcon(fuchsia_8_hub)
