local icefall_0 = DoorSlot("icefall","0")
local icefall_0_hub = DoorSlotHub("icefall","0",icefall_0)
icefall_0:setHubIcon(icefall_0_hub)
local icefall_1 = DoorSlot("icefall","1")
local icefall_1_hub = DoorSlotHub("icefall","1",icefall_1)
icefall_1:setHubIcon(icefall_1_hub)
local icefall_2 = DoorSlot("icefall","2")
local icefall_2_hub = DoorSlotHub("icefall","2",icefall_2)
icefall_2:setHubIcon(icefall_2_hub)
local icefall_3 = DoorSlot("icefall","3")
local icefall_3_hub = DoorSlotHub("icefall","3",icefall_3)
icefall_3:setHubIcon(icefall_3_hub)
local icefall_4 = DoorSlot("icefall","4")
local icefall_4_hub = DoorSlotHub("icefall","4",icefall_4)
icefall_4:setHubIcon(icefall_4_hub)
local icefall_5 = DoorSlot("icefall","5")
local icefall_5_hub = DoorSlotHub("icefall","5",icefall_5)
icefall_5:setHubIcon(icefall_5_hub)
local icefall_6 = DoorSlot("icefall","6")
local icefall_6_hub = DoorSlotHub("icefall","6",icefall_6)
icefall_6:setHubIcon(icefall_6_hub)
local icefall_7 = DoorSlot("icefall","7")
local icefall_7_hub = DoorSlotHub("icefall","7",icefall_7)
icefall_7:setHubIcon(icefall_7_hub)
local icefall_8 = DoorSlot("icefall","8")
local icefall_8_hub = DoorSlotHub("icefall","8",icefall_8)
icefall_8:setHubIcon(icefall_8_hub)
local icefall_9 = DoorSlot("icefall","9")
local icefall_9_hub = DoorSlotHub("icefall","9",icefall_9)
icefall_9:setHubIcon(icefall_9_hub)
local icefall_10 = DoorSlot("icefall","10")
local icefall_10_hub = DoorSlotHub("icefall","10",icefall_10)
icefall_10:setHubIcon(icefall_10_hub)
local icefall_11 = DoorSlot("icefall","11")
local icefall_11_hub = DoorSlotHub("icefall","11",icefall_11)
icefall_11:setHubIcon(icefall_11_hub)
