local indigo_0 = DoorSlot("indigo","0")
local indigo_0_hub = DoorSlotHub("indigo","0",indigo_0)
indigo_0:setHubIcon(indigo_0_hub)
local indigo_1 = DoorSlot("indigo","1")
local indigo_1_hub = DoorSlotHub("indigo","1",indigo_1)
indigo_1:setHubIcon(indigo_1_hub)
local indigo_2 = DoorSlot("indigo","2")
local indigo_2_hub = DoorSlotHub("indigo","2",indigo_2)
indigo_2:setHubIcon(indigo_2_hub)
