local lavender_0 = DoorSlot("lavender","0")
local lavender_0_hub = DoorSlotHub("lavender","0",lavender_0)
lavender_0:setHubIcon(lavender_0_hub)
local lavender_1 = DoorSlot("lavender","1")
local lavender_1_hub = DoorSlotHub("lavender","1",lavender_1)
lavender_1:setHubIcon(lavender_1_hub)
local lavender_2 = DoorSlot("lavender","2")
local lavender_2_hub = DoorSlotHub("lavender","2",lavender_2)
lavender_2:setHubIcon(lavender_2_hub)
local lavender_3 = DoorSlot("lavender","3")
local lavender_3_hub = DoorSlotHub("lavender","3",lavender_3)
lavender_3:setHubIcon(lavender_3_hub)
local lavender_4 = DoorSlot("lavender","4")
local lavender_4_hub = DoorSlotHub("lavender","4",lavender_4)
lavender_4:setHubIcon(lavender_4_hub)
local lavender_5 = DoorSlot("lavender","5")
local lavender_5_hub = DoorSlotHub("lavender","5",lavender_5)
lavender_5:setHubIcon(lavender_5_hub)
