local lost_cave_0 = DoorSlot("lost_cave","0")
local lost_cave_0_hub = DoorSlotHub("lost_cave","0",lost_cave_0)
lost_cave_0:setHubIcon(lost_cave_0_hub)
local lost_cave_1 = DoorSlot("lost_cave","1")
local lost_cave_1_hub = DoorSlotHub("lost_cave","1",lost_cave_1)
lost_cave_1:setHubIcon(lost_cave_1_hub)
local lost_cave_2 = DoorSlot("lost_cave","2")
local lost_cave_2_hub = DoorSlotHub("lost_cave","2",lost_cave_2)
lost_cave_2:setHubIcon(lost_cave_2_hub)
local lost_cave_3 = DoorSlot("lost_cave","3")
local lost_cave_3_hub = DoorSlotHub("lost_cave","3",lost_cave_3)
lost_cave_3:setHubIcon(lost_cave_3_hub)
local lost_cave_4 = DoorSlot("lost_cave","4")
local lost_cave_4_hub = DoorSlotHub("lost_cave","4",lost_cave_4)
lost_cave_4:setHubIcon(lost_cave_4_hub)
local lost_cave_5 = DoorSlot("lost_cave","5")
local lost_cave_5_hub = DoorSlotHub("lost_cave","5",lost_cave_5)
lost_cave_5:setHubIcon(lost_cave_5_hub)
local lost_cave_6 = DoorSlot("lost_cave","6")
local lost_cave_6_hub = DoorSlotHub("lost_cave","6",lost_cave_6)
lost_cave_6:setHubIcon(lost_cave_6_hub)
local lost_cave_7 = DoorSlot("lost_cave","7")
local lost_cave_7_hub = DoorSlotHub("lost_cave","7",lost_cave_7)
lost_cave_7:setHubIcon(lost_cave_7_hub)
local lost_cave_8 = DoorSlot("lost_cave","8")
local lost_cave_8_hub = DoorSlotHub("lost_cave","8",lost_cave_8)
lost_cave_8:setHubIcon(lost_cave_8_hub)
local lost_cave_9 = DoorSlot("lost_cave","9")
local lost_cave_9_hub = DoorSlotHub("lost_cave","9",lost_cave_9)
lost_cave_9:setHubIcon(lost_cave_9_hub)
local lost_cave_10 = DoorSlot("lost_cave","10")
local lost_cave_10_hub = DoorSlotHub("lost_cave","10",lost_cave_10)
lost_cave_10:setHubIcon(lost_cave_10_hub)
local lost_cave_11 = DoorSlot("lost_cave","11")
local lost_cave_11_hub = DoorSlotHub("lost_cave","11",lost_cave_11)
lost_cave_11:setHubIcon(lost_cave_11_hub)
local lost_cave_12 = DoorSlot("lost_cave","12")
local lost_cave_12_hub = DoorSlotHub("lost_cave","12",lost_cave_12)
lost_cave_12:setHubIcon(lost_cave_12_hub)
local lost_cave_13 = DoorSlot("lost_cave","13")
local lost_cave_13_hub = DoorSlotHub("lost_cave","13",lost_cave_13)
lost_cave_13:setHubIcon(lost_cave_13_hub)
local lost_cave_14 = DoorSlot("lost_cave","14")
local lost_cave_14_hub = DoorSlotHub("lost_cave","14",lost_cave_14)
lost_cave_14:setHubIcon(lost_cave_14_hub)
local lost_cave_15 = DoorSlot("lost_cave","15")
local lost_cave_15_hub = DoorSlotHub("lost_cave","15",lost_cave_15)
lost_cave_15:setHubIcon(lost_cave_15_hub)
local lost_cave_16 = DoorSlot("lost_cave","16")
local lost_cave_16_hub = DoorSlotHub("lost_cave","16",lost_cave_16)
lost_cave_16:setHubIcon(lost_cave_16_hub)
local lost_cave_17 = DoorSlot("lost_cave","17")
local lost_cave_17_hub = DoorSlotHub("lost_cave","17",lost_cave_17)
lost_cave_17:setHubIcon(lost_cave_17_hub)
local lost_cave_18 = DoorSlot("lost_cave","18")
local lost_cave_18_hub = DoorSlotHub("lost_cave","18",lost_cave_18)
lost_cave_18:setHubIcon(lost_cave_18_hub)
local lost_cave_19 = DoorSlot("lost_cave","19")
local lost_cave_19_hub = DoorSlotHub("lost_cave","19",lost_cave_19)
lost_cave_19:setHubIcon(lost_cave_19_hub)
local lost_cave_20 = DoorSlot("lost_cave","20")
local lost_cave_20_hub = DoorSlotHub("lost_cave","20",lost_cave_20)
lost_cave_20:setHubIcon(lost_cave_20_hub)
local lost_cave_21 = DoorSlot("lost_cave","21")
local lost_cave_21_hub = DoorSlotHub("lost_cave","21",lost_cave_21)
lost_cave_21:setHubIcon(lost_cave_21_hub)
local lost_cave_22 = DoorSlot("lost_cave","22")
local lost_cave_22_hub = DoorSlotHub("lost_cave","22",lost_cave_22)
lost_cave_22:setHubIcon(lost_cave_22_hub)
local lost_cave_23 = DoorSlot("lost_cave","23")
local lost_cave_23_hub = DoorSlotHub("lost_cave","23",lost_cave_23)
lost_cave_23:setHubIcon(lost_cave_23_hub)
local lost_cave_24 = DoorSlot("lost_cave","24")
local lost_cave_24_hub = DoorSlotHub("lost_cave","24",lost_cave_24)
lost_cave_24:setHubIcon(lost_cave_24_hub)
local lost_cave_25 = DoorSlot("lost_cave","25")
local lost_cave_25_hub = DoorSlotHub("lost_cave","25",lost_cave_25)
lost_cave_25:setHubIcon(lost_cave_25_hub)
local lost_cave_26 = DoorSlot("lost_cave","26")
local lost_cave_26_hub = DoorSlotHub("lost_cave","26",lost_cave_26)
lost_cave_26:setHubIcon(lost_cave_26_hub)
local lost_cave_27 = DoorSlot("lost_cave","27")
local lost_cave_27_hub = DoorSlotHub("lost_cave","27",lost_cave_27)
lost_cave_27:setHubIcon(lost_cave_27_hub)
local lost_cave_28 = DoorSlot("lost_cave","28")
local lost_cave_28_hub = DoorSlotHub("lost_cave","28",lost_cave_28)
lost_cave_28:setHubIcon(lost_cave_28_hub)
local lost_cave_29 = DoorSlot("lost_cave","29")
local lost_cave_29_hub = DoorSlotHub("lost_cave","29",lost_cave_29)
lost_cave_29:setHubIcon(lost_cave_29_hub)
local lost_cave_30 = DoorSlot("lost_cave","30")
local lost_cave_30_hub = DoorSlotHub("lost_cave","30",lost_cave_30)
lost_cave_30:setHubIcon(lost_cave_30_hub)
local lost_cave_31 = DoorSlot("lost_cave","31")
local lost_cave_31_hub = DoorSlotHub("lost_cave","31",lost_cave_31)
lost_cave_31:setHubIcon(lost_cave_31_hub)
local lost_cave_32 = DoorSlot("lost_cave","32")
local lost_cave_32_hub = DoorSlotHub("lost_cave","32",lost_cave_32)
lost_cave_32:setHubIcon(lost_cave_32_hub)
local lost_cave_33 = DoorSlot("lost_cave","33")
local lost_cave_33_hub = DoorSlotHub("lost_cave","33",lost_cave_33)
lost_cave_33:setHubIcon(lost_cave_33_hub)
local lost_cave_34 = DoorSlot("lost_cave","34")
local lost_cave_34_hub = DoorSlotHub("lost_cave","34",lost_cave_34)
lost_cave_34:setHubIcon(lost_cave_34_hub)
local lost_cave_35 = DoorSlot("lost_cave","35")
local lost_cave_35_hub = DoorSlotHub("lost_cave","35",lost_cave_35)
lost_cave_35:setHubIcon(lost_cave_35_hub)
local lost_cave_36 = DoorSlot("lost_cave","36")
local lost_cave_36_hub = DoorSlotHub("lost_cave","36",lost_cave_36)
lost_cave_36:setHubIcon(lost_cave_36_hub)
