local mansion_0 = DoorSlot("mansion","0")
local mansion_0_hub = DoorSlotHub("mansion","0",mansion_0)
mansion_0:setHubIcon(mansion_0_hub)
local mansion_1 = DoorSlot("mansion","1")
local mansion_1_hub = DoorSlotHub("mansion","1",mansion_1)
mansion_1:setHubIcon(mansion_1_hub)
local mansion_2 = DoorSlot("mansion","2")
local mansion_2_hub = DoorSlotHub("mansion","2",mansion_2)
mansion_2:setHubIcon(mansion_2_hub)
local mansion_3 = DoorSlot("mansion","3")
local mansion_3_hub = DoorSlotHub("mansion","3",mansion_3)
mansion_3:setHubIcon(mansion_3_hub)
local mansion_4 = DoorSlot("mansion","4")
local mansion_4_hub = DoorSlotHub("mansion","4",mansion_4)
mansion_4:setHubIcon(mansion_4_hub)
local mansion_5 = DoorSlot("mansion","5")
local mansion_5_hub = DoorSlotHub("mansion","5",mansion_5)
mansion_5:setHubIcon(mansion_5_hub)
local mansion_6 = DoorSlot("mansion","6")
local mansion_6_hub = DoorSlotHub("mansion","6",mansion_6)
mansion_6:setHubIcon(mansion_6_hub)
local mansion_7 = DoorSlot("mansion","7")
local mansion_7_hub = DoorSlotHub("mansion","7",mansion_7)
mansion_7:setHubIcon(mansion_7_hub)
local mansion_8 = DoorSlot("mansion","8")
local mansion_8_hub = DoorSlotHub("mansion","8",mansion_8)
mansion_8:setHubIcon(mansion_8_hub)
local mansion_9 = DoorSlot("mansion","9")
local mansion_9_hub = DoorSlotHub("mansion","9",mansion_9)
mansion_9:setHubIcon(mansion_9_hub)
local mansion_10 = DoorSlot("mansion","10")
local mansion_10_hub = DoorSlotHub("mansion","10",mansion_10)
mansion_10:setHubIcon(mansion_10_hub)
