local mt_ember_0 = DoorSlot("mt_ember","0")
local mt_ember_0_hub = DoorSlotHub("mt_ember","0",mt_ember_0)
mt_ember_0:setHubIcon(mt_ember_0_hub)
local mt_ember_1 = DoorSlot("mt_ember","1")
local mt_ember_1_hub = DoorSlotHub("mt_ember","1",mt_ember_1)
mt_ember_1:setHubIcon(mt_ember_1_hub)
local mt_ember_2 = DoorSlot("mt_ember","2")
local mt_ember_2_hub = DoorSlotHub("mt_ember","2",mt_ember_2)
mt_ember_2:setHubIcon(mt_ember_2_hub)
local mt_ember_3 = DoorSlot("mt_ember","3")
local mt_ember_3_hub = DoorSlotHub("mt_ember","3",mt_ember_3)
mt_ember_3:setHubIcon(mt_ember_3_hub)
local mt_ember_4 = DoorSlot("mt_ember","4")
local mt_ember_4_hub = DoorSlotHub("mt_ember","4",mt_ember_4)
mt_ember_4:setHubIcon(mt_ember_4_hub)
local mt_ember_5 = DoorSlot("mt_ember","5")
local mt_ember_5_hub = DoorSlotHub("mt_ember","5",mt_ember_5)
mt_ember_5:setHubIcon(mt_ember_5_hub)
local mt_ember_6 = DoorSlot("mt_ember","6")
local mt_ember_6_hub = DoorSlotHub("mt_ember","6",mt_ember_6)
mt_ember_6:setHubIcon(mt_ember_6_hub)
local mt_ember_7 = DoorSlot("mt_ember","7")
local mt_ember_7_hub = DoorSlotHub("mt_ember","7",mt_ember_7)
mt_ember_7:setHubIcon(mt_ember_7_hub)
local mt_ember_8 = DoorSlot("mt_ember","8")
local mt_ember_8_hub = DoorSlotHub("mt_ember","8",mt_ember_8)
mt_ember_8:setHubIcon(mt_ember_8_hub)
local mt_ember_9 = DoorSlot("mt_ember","9")
local mt_ember_9_hub = DoorSlotHub("mt_ember","9",mt_ember_9)
mt_ember_9:setHubIcon(mt_ember_9_hub)
local mt_ember_10 = DoorSlot("mt_ember","10")
local mt_ember_10_hub = DoorSlotHub("mt_ember","10",mt_ember_10)
mt_ember_10:setHubIcon(mt_ember_10_hub)
