local mt_moon_0 = DoorSlot("mt_moon","0")
local mt_moon_0_hub = DoorSlotHub("mt_moon","0",mt_moon_0)
mt_moon_0:setHubIcon(mt_moon_0_hub)
local mt_moon_1 = DoorSlot("mt_moon","1")
local mt_moon_1_hub = DoorSlotHub("mt_moon","1",mt_moon_1)
mt_moon_1:setHubIcon(mt_moon_1_hub)
local mt_moon_2 = DoorSlot("mt_moon","2")
local mt_moon_2_hub = DoorSlotHub("mt_moon","2",mt_moon_2)
mt_moon_2:setHubIcon(mt_moon_2_hub)
local mt_moon_3 = DoorSlot("mt_moon","3")
local mt_moon_3_hub = DoorSlotHub("mt_moon","3",mt_moon_3)
mt_moon_3:setHubIcon(mt_moon_3_hub)
