local navel_rock_0 = DoorSlot("navel_rock","0")
local navel_rock_0_hub = DoorSlotHub("navel_rock","0",navel_rock_0)
navel_rock_0:setHubIcon(navel_rock_0_hub)
local navel_rock_1 = DoorSlot("navel_rock","1")
local navel_rock_1_hub = DoorSlotHub("navel_rock","1",navel_rock_1)
navel_rock_1:setHubIcon(navel_rock_1_hub)
local navel_rock_2 = DoorSlot("navel_rock","2")
local navel_rock_2_hub = DoorSlotHub("navel_rock","2",navel_rock_2)
navel_rock_2:setHubIcon(navel_rock_2_hub)
