local one_0 = DoorSlot("one","0")
local one_0_hub = DoorSlotHub("one","0",one_0)
one_0:setHubIcon(one_0_hub)
local one_1 = DoorSlot("one","1")
local one_1_hub = DoorSlotHub("one","1",one_1)
one_1:setHubIcon(one_1_hub)
local one_2 = DoorSlot("one","2")
local one_2_hub = DoorSlotHub("one","2",one_2)
one_2:setHubIcon(one_2_hub)
local one_3 = DoorSlot("one","3")
local one_3_hub = DoorSlotHub("one","3",one_3)
one_3:setHubIcon(one_3_hub)
local one_4 = DoorSlot("one","4")
local one_4_hub = DoorSlotHub("one","4",one_4)
one_4:setHubIcon(one_4_hub)
local one_5 = DoorSlot("one","5")
local one_5_hub = DoorSlotHub("one","5",one_5)
one_5:setHubIcon(one_5_hub)
