local pewter_0 = DoorSlot("pewter","0")
local pewter_0_hub = DoorSlotHub("pewter","0",pewter_0)
pewter_0:setHubIcon(pewter_0_hub)
local pewter_1 = DoorSlot("pewter","1")
local pewter_1_hub = DoorSlotHub("pewter","1",pewter_1)
pewter_1:setHubIcon(pewter_1_hub)
local pewter_2 = DoorSlot("pewter","2")
local pewter_2_hub = DoorSlotHub("pewter","2",pewter_2)
pewter_2:setHubIcon(pewter_2_hub)
local pewter_3 = DoorSlot("pewter","3")
local pewter_3_hub = DoorSlotHub("pewter","3",pewter_3)
pewter_3:setHubIcon(pewter_3_hub)
local pewter_4 = DoorSlot("pewter","4")
local pewter_4_hub = DoorSlotHub("pewter","4",pewter_4)
pewter_4:setHubIcon(pewter_4_hub)
local pewter_5 = DoorSlot("pewter","5")
local pewter_5_hub = DoorSlotHub("pewter","5",pewter_5)
pewter_5:setHubIcon(pewter_5_hub)
local pewter_6 = DoorSlot("pewter","6")
local pewter_6_hub = DoorSlotHub("pewter","6",pewter_6)
pewter_6:setHubIcon(pewter_6_hub)
