local rocket_hideout_0 = DoorSlot("rocket_hideout","0")
local rocket_hideout_0_hub = DoorSlotHub("rocket_hideout","0",rocket_hideout_0)
rocket_hideout_0:setHubIcon(rocket_hideout_0_hub)
local rocket_hideout_1 = DoorSlot("rocket_hideout","1")
local rocket_hideout_1_hub = DoorSlotHub("rocket_hideout","1",rocket_hideout_1)
rocket_hideout_1:setHubIcon(rocket_hideout_1_hub)
local rocket_hideout_2 = DoorSlot("rocket_hideout","2")
local rocket_hideout_2_hub = DoorSlotHub("rocket_hideout","2",rocket_hideout_2)
rocket_hideout_2:setHubIcon(rocket_hideout_2_hub)
local rocket_hideout_3 = DoorSlot("rocket_hideout","3")
local rocket_hideout_3_hub = DoorSlotHub("rocket_hideout","3",rocket_hideout_3)
rocket_hideout_3:setHubIcon(rocket_hideout_3_hub)
local rocket_hideout_4 = DoorSlot("rocket_hideout","4")
local rocket_hideout_4_hub = DoorSlotHub("rocket_hideout","4",rocket_hideout_4)
rocket_hideout_4:setHubIcon(rocket_hideout_4_hub)
