local saffron_0 = DoorSlot("saffron","0")
local saffron_0_hub = DoorSlotHub("saffron","0",saffron_0)
saffron_0:setHubIcon(saffron_0_hub)
local saffron_1 = DoorSlot("saffron","1")
local saffron_1_hub = DoorSlotHub("saffron","1",saffron_1)
saffron_1:setHubIcon(saffron_1_hub)
local saffron_2 = DoorSlot("saffron","2")
local saffron_2_hub = DoorSlotHub("saffron","2",saffron_2)
saffron_2:setHubIcon(saffron_2_hub)
local saffron_3 = DoorSlot("saffron","3")
local saffron_3_hub = DoorSlotHub("saffron","3",saffron_3)
saffron_3:setHubIcon(saffron_3_hub)
local saffron_4 = DoorSlot("saffron","4")
local saffron_4_hub = DoorSlotHub("saffron","4",saffron_4)
saffron_4:setHubIcon(saffron_4_hub)
local saffron_5 = DoorSlot("saffron","5")
local saffron_5_hub = DoorSlotHub("saffron","5",saffron_5)
saffron_5:setHubIcon(saffron_5_hub)
local saffron_6 = DoorSlot("saffron","6")
local saffron_6_hub = DoorSlotHub("saffron","6",saffron_6)
saffron_6:setHubIcon(saffron_6_hub)
local saffron_7 = DoorSlot("saffron","7")
local saffron_7_hub = DoorSlotHub("saffron","7",saffron_7)
saffron_7:setHubIcon(saffron_7_hub)
local saffron_8 = DoorSlot("saffron","8")
local saffron_8_hub = DoorSlotHub("saffron","8",saffron_8)
saffron_8:setHubIcon(saffron_8_hub)
local saffron_9 = DoorSlot("saffron","9")
local saffron_9_hub = DoorSlotHub("saffron","9",saffron_9)
saffron_9:setHubIcon(saffron_9_hub)
local saffron_10 = DoorSlot("saffron","10")
local saffron_10_hub = DoorSlotHub("saffron","10",saffron_10)
saffron_10:setHubIcon(saffron_10_hub)
local saffron_11 = DoorSlot("saffron","11")
local saffron_11_hub = DoorSlotHub("saffron","11",saffron_11)
saffron_11:setHubIcon(saffron_11_hub)
local saffron_12 = DoorSlot("saffron","12")
local saffron_12_hub = DoorSlotHub("saffron","12",saffron_12)
saffron_12:setHubIcon(saffron_12_hub)
