local seafoam_islands_0 = DoorSlot("seafoam_islands","0")
local seafoam_islands_0_hub = DoorSlotHub("seafoam_islands","0",seafoam_islands_0)
seafoam_islands_0:setHubIcon(seafoam_islands_0_hub)
local seafoam_islands_1 = DoorSlot("seafoam_islands","1")
local seafoam_islands_1_hub = DoorSlotHub("seafoam_islands","1",seafoam_islands_1)
seafoam_islands_1:setHubIcon(seafoam_islands_1_hub)
local seafoam_islands_2 = DoorSlot("seafoam_islands","2")
local seafoam_islands_2_hub = DoorSlotHub("seafoam_islands","2",seafoam_islands_2)
seafoam_islands_2:setHubIcon(seafoam_islands_2_hub)
local seafoam_islands_3 = DoorSlot("seafoam_islands","3")
local seafoam_islands_3_hub = DoorSlotHub("seafoam_islands","3",seafoam_islands_3)
seafoam_islands_3:setHubIcon(seafoam_islands_3_hub)
local seafoam_islands_4 = DoorSlot("seafoam_islands","4")
local seafoam_islands_4_hub = DoorSlotHub("seafoam_islands","4",seafoam_islands_4)
seafoam_islands_4:setHubIcon(seafoam_islands_4_hub)
local seafoam_islands_5 = DoorSlot("seafoam_islands","5")
local seafoam_islands_5_hub = DoorSlotHub("seafoam_islands","5",seafoam_islands_5)
seafoam_islands_5:setHubIcon(seafoam_islands_5_hub)
local seafoam_islands_6 = DoorSlot("seafoam_islands","6")
local seafoam_islands_6_hub = DoorSlotHub("seafoam_islands","6",seafoam_islands_6)
seafoam_islands_6:setHubIcon(seafoam_islands_6_hub)
local seafoam_islands_7 = DoorSlot("seafoam_islands","7")
local seafoam_islands_7_hub = DoorSlotHub("seafoam_islands","7",seafoam_islands_7)
seafoam_islands_7:setHubIcon(seafoam_islands_7_hub)
local seafoam_islands_8 = DoorSlot("seafoam_islands","8")
local seafoam_islands_8_hub = DoorSlotHub("seafoam_islands","8",seafoam_islands_8)
seafoam_islands_8:setHubIcon(seafoam_islands_8_hub)
local seafoam_islands_9 = DoorSlot("seafoam_islands","9")
local seafoam_islands_9_hub = DoorSlotHub("seafoam_islands","9",seafoam_islands_9)
seafoam_islands_9:setHubIcon(seafoam_islands_9_hub)
local seafoam_islands_10 = DoorSlot("seafoam_islands","10")
local seafoam_islands_10_hub = DoorSlotHub("seafoam_islands","10",seafoam_islands_10)
seafoam_islands_10:setHubIcon(seafoam_islands_10_hub)
local seafoam_islands_11 = DoorSlot("seafoam_islands","11")
local seafoam_islands_11_hub = DoorSlotHub("seafoam_islands","11",seafoam_islands_11)
seafoam_islands_11:setHubIcon(seafoam_islands_11_hub)
local seafoam_islands_12 = DoorSlot("seafoam_islands","12")
local seafoam_islands_12_hub = DoorSlotHub("seafoam_islands","12",seafoam_islands_12)
seafoam_islands_12:setHubIcon(seafoam_islands_12_hub)
local seafoam_islands_13 = DoorSlot("seafoam_islands","13")
local seafoam_islands_13_hub = DoorSlotHub("seafoam_islands","13",seafoam_islands_13)
seafoam_islands_13:setHubIcon(seafoam_islands_13_hub)
local seafoam_islands_14 = DoorSlot("seafoam_islands","14")
local seafoam_islands_14_hub = DoorSlotHub("seafoam_islands","14",seafoam_islands_14)
seafoam_islands_14:setHubIcon(seafoam_islands_14_hub)
local seafoam_islands_15 = DoorSlot("seafoam_islands","15")
local seafoam_islands_15_hub = DoorSlotHub("seafoam_islands","15",seafoam_islands_15)
seafoam_islands_15:setHubIcon(seafoam_islands_15_hub)
local seafoam_islands_16 = DoorSlot("seafoam_islands","16")
local seafoam_islands_16_hub = DoorSlotHub("seafoam_islands","16",seafoam_islands_16)
seafoam_islands_16:setHubIcon(seafoam_islands_16_hub)
local seafoam_islands_17 = DoorSlot("seafoam_islands","17")
local seafoam_islands_17_hub = DoorSlotHub("seafoam_islands","17",seafoam_islands_17)
seafoam_islands_17:setHubIcon(seafoam_islands_17_hub)
local seafoam_islands_18 = DoorSlot("seafoam_islands","18")
local seafoam_islands_18_hub = DoorSlotHub("seafoam_islands","18",seafoam_islands_18)
seafoam_islands_18:setHubIcon(seafoam_islands_18_hub)
