local seven_0 = DoorSlot("seven","0")
local seven_0_hub = DoorSlotHub("seven","0",seven_0)
seven_0:setHubIcon(seven_0_hub)
local seven_1 = DoorSlot("seven","1")
local seven_1_hub = DoorSlotHub("seven","1",seven_1)
seven_1:setHubIcon(seven_1_hub)
local seven_2 = DoorSlot("seven","2")
local seven_2_hub = DoorSlotHub("seven","2",seven_2)
seven_2:setHubIcon(seven_2_hub)
local seven_3 = DoorSlot("seven","3")
local seven_3_hub = DoorSlotHub("seven","3",seven_3)
seven_3:setHubIcon(seven_3_hub)
local seven_4 = DoorSlot("seven","4")
local seven_4_hub = DoorSlotHub("seven","4",seven_4)
seven_4:setHubIcon(seven_4_hub)
local seven_5 = DoorSlot("seven","5")
local seven_5_hub = DoorSlotHub("seven","5",seven_5)
seven_5:setHubIcon(seven_5_hub)
local seven_6 = DoorSlot("seven","6")
local seven_6_hub = DoorSlotHub("seven","6",seven_6)
seven_6:setHubIcon(seven_6_hub)
local seven_7 = DoorSlot("seven","7")
local seven_7_hub = DoorSlotHub("seven","7",seven_7)
seven_7:setHubIcon(seven_7_hub)
local seven_8 = DoorSlot("seven","8")
local seven_8_hub = DoorSlotHub("seven","8",seven_8)
seven_8:setHubIcon(seven_8_hub)
local seven_9 = DoorSlot("seven","9")
local seven_9_hub = DoorSlotHub("seven","9",seven_9)
seven_9:setHubIcon(seven_9_hub)
local seven_10 = DoorSlot("seven","10")
local seven_10_hub = DoorSlotHub("seven","10",seven_10)
seven_10:setHubIcon(seven_10_hub)
local seven_11 = DoorSlot("seven","11")
local seven_11_hub = DoorSlotHub("seven","11",seven_11)
seven_11:setHubIcon(seven_11_hub)
local seven_12 = DoorSlot("seven","12")
local seven_12_hub = DoorSlotHub("seven","12",seven_12)
seven_12:setHubIcon(seven_12_hub)
local seven_13 = DoorSlot("seven","13")
local seven_13_hub = DoorSlotHub("seven","13",seven_13)
seven_13:setHubIcon(seven_13_hub)
