local six_0 = DoorSlot("six","0")
local six_0_hub = DoorSlotHub("six","0",six_0)
six_0:setHubIcon(six_0_hub)
local six_1 = DoorSlot("six","1")
local six_1_hub = DoorSlotHub("six","1",six_1)
six_1:setHubIcon(six_1_hub)
local six_2 = DoorSlot("six","2")
local six_2_hub = DoorSlotHub("six","2",six_2)
six_2:setHubIcon(six_2_hub)
local six_3 = DoorSlot("six","3")
local six_3_hub = DoorSlotHub("six","3",six_3)
six_3:setHubIcon(six_3_hub)
local six_4 = DoorSlot("six","4")
local six_4_hub = DoorSlotHub("six","4",six_4)
six_4:setHubIcon(six_4_hub)
local six_5 = DoorSlot("six","5")
local six_5_hub = DoorSlotHub("six","5",six_5)
six_5:setHubIcon(six_5_hub)
local six_6 = DoorSlot("six","6")
local six_6_hub = DoorSlotHub("six","6",six_6)
six_6:setHubIcon(six_6_hub)
local six_7 = DoorSlot("six","7")
local six_7_hub = DoorSlotHub("six","7",six_7)
six_7:setHubIcon(six_7_hub)
