local ss_anne_0 = DoorSlot("ss_anne","0")
local ss_anne_0_hub = DoorSlotHub("ss_anne","0",ss_anne_0)
ss_anne_0:setHubIcon(ss_anne_0_hub)
local ss_anne_1 = DoorSlot("ss_anne","1")
local ss_anne_1_hub = DoorSlotHub("ss_anne","1",ss_anne_1)
ss_anne_1:setHubIcon(ss_anne_1_hub)
local ss_anne_2 = DoorSlot("ss_anne","2")
local ss_anne_2_hub = DoorSlotHub("ss_anne","2",ss_anne_2)
ss_anne_2:setHubIcon(ss_anne_2_hub)
local ss_anne_3 = DoorSlot("ss_anne","3")
local ss_anne_3_hub = DoorSlotHub("ss_anne","3",ss_anne_3)
ss_anne_3:setHubIcon(ss_anne_3_hub)
local ss_anne_4 = DoorSlot("ss_anne","4")
local ss_anne_4_hub = DoorSlotHub("ss_anne","4",ss_anne_4)
ss_anne_4:setHubIcon(ss_anne_4_hub)
local ss_anne_5 = DoorSlot("ss_anne","5")
local ss_anne_5_hub = DoorSlotHub("ss_anne","5",ss_anne_5)
ss_anne_5:setHubIcon(ss_anne_5_hub)
local ss_anne_6 = DoorSlot("ss_anne","6")
local ss_anne_6_hub = DoorSlotHub("ss_anne","6",ss_anne_6)
ss_anne_6:setHubIcon(ss_anne_6_hub)
local ss_anne_7 = DoorSlot("ss_anne","7")
local ss_anne_7_hub = DoorSlotHub("ss_anne","7",ss_anne_7)
ss_anne_7:setHubIcon(ss_anne_7_hub)
local ss_anne_8 = DoorSlot("ss_anne","8")
local ss_anne_8_hub = DoorSlotHub("ss_anne","8",ss_anne_8)
ss_anne_8:setHubIcon(ss_anne_8_hub)
local ss_anne_9 = DoorSlot("ss_anne","9")
local ss_anne_9_hub = DoorSlotHub("ss_anne","9",ss_anne_9)
ss_anne_9:setHubIcon(ss_anne_9_hub)
local ss_anne_10 = DoorSlot("ss_anne","10")
local ss_anne_10_hub = DoorSlotHub("ss_anne","10",ss_anne_10)
ss_anne_10:setHubIcon(ss_anne_10_hub)
local ss_anne_11 = DoorSlot("ss_anne","11")
local ss_anne_11_hub = DoorSlotHub("ss_anne","11",ss_anne_11)
ss_anne_11:setHubIcon(ss_anne_11_hub)
local ss_anne_12 = DoorSlot("ss_anne","12")
local ss_anne_12_hub = DoorSlotHub("ss_anne","12",ss_anne_12)
ss_anne_12:setHubIcon(ss_anne_12_hub)
local ss_anne_13 = DoorSlot("ss_anne","13")
local ss_anne_13_hub = DoorSlotHub("ss_anne","13",ss_anne_13)
ss_anne_13:setHubIcon(ss_anne_13_hub)
local ss_anne_14 = DoorSlot("ss_anne","14")
local ss_anne_14_hub = DoorSlotHub("ss_anne","14",ss_anne_14)
ss_anne_14:setHubIcon(ss_anne_14_hub)
local ss_anne_15 = DoorSlot("ss_anne","15")
local ss_anne_15_hub = DoorSlotHub("ss_anne","15",ss_anne_15)
ss_anne_15:setHubIcon(ss_anne_15_hub)
local ss_anne_16 = DoorSlot("ss_anne","16")
local ss_anne_16_hub = DoorSlotHub("ss_anne","16",ss_anne_16)
ss_anne_16:setHubIcon(ss_anne_16_hub)
local ss_anne_17 = DoorSlot("ss_anne","17")
local ss_anne_17_hub = DoorSlotHub("ss_anne","17",ss_anne_17)
ss_anne_17:setHubIcon(ss_anne_17_hub)
local ss_anne_18 = DoorSlot("ss_anne","18")
local ss_anne_18_hub = DoorSlotHub("ss_anne","18",ss_anne_18)
ss_anne_18:setHubIcon(ss_anne_18_hub)
local ss_anne_19 = DoorSlot("ss_anne","19")
local ss_anne_19_hub = DoorSlotHub("ss_anne","19",ss_anne_19)
ss_anne_19:setHubIcon(ss_anne_19_hub)
local ss_anne_20 = DoorSlot("ss_anne","20")
local ss_anne_20_hub = DoorSlotHub("ss_anne","20",ss_anne_20)
ss_anne_20:setHubIcon(ss_anne_20_hub)
local ss_anne_21 = DoorSlot("ss_anne","21")
local ss_anne_21_hub = DoorSlotHub("ss_anne","21",ss_anne_21)
ss_anne_21:setHubIcon(ss_anne_21_hub)
local ss_anne_22 = DoorSlot("ss_anne","22")
local ss_anne_22_hub = DoorSlotHub("ss_anne","22",ss_anne_22)
ss_anne_22:setHubIcon(ss_anne_22_hub)
local ss_anne_23 = DoorSlot("ss_anne","23")
local ss_anne_23_hub = DoorSlotHub("ss_anne","23",ss_anne_23)
ss_anne_23:setHubIcon(ss_anne_23_hub)
local ss_anne_24 = DoorSlot("ss_anne","24")
local ss_anne_24_hub = DoorSlotHub("ss_anne","24",ss_anne_24)
ss_anne_24:setHubIcon(ss_anne_24_hub)
local ss_anne_25 = DoorSlot("ss_anne","25")
local ss_anne_25_hub = DoorSlotHub("ss_anne","25",ss_anne_25)
ss_anne_25:setHubIcon(ss_anne_25_hub)
