local three_0 = DoorSlot("three","0")
local three_0_hub = DoorSlotHub("three","0",three_0)
three_0:setHubIcon(three_0_hub)
local three_1 = DoorSlot("three","1")
local three_1_hub = DoorSlotHub("three","1",three_1)
three_1:setHubIcon(three_1_hub)
local three_2 = DoorSlot("three","2")
local three_2_hub = DoorSlotHub("three","2",three_2)
three_2:setHubIcon(three_2_hub)
local three_3 = DoorSlot("three","3")
local three_3_hub = DoorSlotHub("three","3",three_3)
three_3:setHubIcon(three_3_hub)
local three_4 = DoorSlot("three","4")
local three_4_hub = DoorSlotHub("three","4",three_4)
three_4:setHubIcon(three_4_hub)
local three_5 = DoorSlot("three","5")
local three_5_hub = DoorSlotHub("three","5",three_5)
three_5:setHubIcon(three_5_hub)
local three_6 = DoorSlot("three","6")
local three_6_hub = DoorSlotHub("three","6",three_6)
three_6:setHubIcon(three_6_hub)
local three_7 = DoorSlot("three","7")
local three_7_hub = DoorSlotHub("three","7",three_7)
three_7:setHubIcon(three_7_hub)
local three_8 = DoorSlot("three","8")
local three_8_hub = DoorSlotHub("three","8",three_8)
three_8:setHubIcon(three_8_hub)
local three_9 = DoorSlot("three","9")
local three_9_hub = DoorSlotHub("three","9",three_9)
three_9:setHubIcon(three_9_hub)
