local two_0 = DoorSlot("two","0")
local two_0_hub = DoorSlotHub("two","0",two_0)
two_0:setHubIcon(two_0_hub)
local two_1 = DoorSlot("two","1")
local two_1_hub = DoorSlotHub("two","1",two_1)
two_1:setHubIcon(two_1_hub)
local two_2 = DoorSlot("two","2")
local two_2_hub = DoorSlotHub("two","2",two_2)
two_2:setHubIcon(two_2_hub)
local two_3 = DoorSlot("two","3")
local two_3_hub = DoorSlotHub("two","3",two_3)
two_3:setHubIcon(two_3_hub)
local two_4 = DoorSlot("two","4")
local two_4_hub = DoorSlotHub("two","4",two_4)
two_4:setHubIcon(two_4_hub)
