local vermilion_0 = DoorSlot("vermilion","0")
local vermilion_0_hub = DoorSlotHub("vermilion","0",vermilion_0)
vermilion_0:setHubIcon(vermilion_0_hub)
local vermilion_1 = DoorSlot("vermilion","1")
local vermilion_1_hub = DoorSlotHub("vermilion","1",vermilion_1)
vermilion_1:setHubIcon(vermilion_1_hub)
local vermilion_2 = DoorSlot("vermilion","2")
local vermilion_2_hub = DoorSlotHub("vermilion","2",vermilion_2)
vermilion_2:setHubIcon(vermilion_2_hub)
local vermilion_3 = DoorSlot("vermilion","3")
local vermilion_3_hub = DoorSlotHub("vermilion","3",vermilion_3)
vermilion_3:setHubIcon(vermilion_3_hub)
local vermilion_4 = DoorSlot("vermilion","4")
local vermilion_4_hub = DoorSlotHub("vermilion","4",vermilion_4)
vermilion_4:setHubIcon(vermilion_4_hub)
local vermilion_5 = DoorSlot("vermilion","5")
local vermilion_5_hub = DoorSlotHub("vermilion","5",vermilion_5)
vermilion_5:setHubIcon(vermilion_5_hub)
local vermilion_6 = DoorSlot("vermilion","6")
local vermilion_6_hub = DoorSlotHub("vermilion","6",vermilion_6)
vermilion_6:setHubIcon(vermilion_6_hub)
local vermilion_7 = DoorSlot("vermilion","7")
local vermilion_7_hub = DoorSlotHub("vermilion","7",vermilion_7)
vermilion_7:setHubIcon(vermilion_7_hub)
