local viridian_0 = DoorSlot("viridian","0")
local viridian_0_hub = DoorSlotHub("viridian","0",viridian_0)
viridian_0:setHubIcon(viridian_0_hub)
local viridian_1 = DoorSlot("viridian","1")
local viridian_1_hub = DoorSlotHub("viridian","1",viridian_1)
viridian_1:setHubIcon(viridian_1_hub)
local viridian_2 = DoorSlot("viridian","2")
local viridian_2_hub = DoorSlotHub("viridian","2",viridian_2)
viridian_2:setHubIcon(viridian_2_hub)
local viridian_3 = DoorSlot("viridian","3")
local viridian_3_hub = DoorSlotHub("viridian","3",viridian_3)
viridian_3:setHubIcon(viridian_3_hub)
local viridian_4 = DoorSlot("viridian","4")
local viridian_4_hub = DoorSlotHub("viridian","4",viridian_4)
viridian_4:setHubIcon(viridian_4_hub)
